_base_: place_a2b_left__shared_latent__target_franka__m10__target_val__grl_kl.yaml

model:
  lvp_action_source: idm
  idm_input_source: rgb_patch

idm:
  model:
    idm:
      patch_size: 16
      add_action_token: true
      concatenate_gripper_state: false

train:
  output_dir: ""

wandb:
  name: robotwin_place_a2b_left_shared_latent_target_franka_m10_target_val_grl_kl_idm_rgb_patch
